# Datadog Agent with Logs, APM, Processes, and System Probe enabled
# https://github.com/DataDog/helm-charts/blob/main/charts/datadog/values.yaml
targetSystem: "linux"
datadog:
  site:  us3.datadoghq.com
  apiKeyExistingSecret: datadog-api-key-ingestion
  clusterName: talk2robots
  tags: []
  # datadog.kubelet.tlsVerify should be `false` on kind and minikube
  # to establish communication with the kubelet
  kubelet:
    tlsVerify: "false"

  # datadog.collectEvents -- Enables this to start event collection from the kubernetes API
  ## ref: https://docs.datadoghq.com/agent/kubernetes/#event-collection
  collectEvents: false
  env:
    - name: DD_DOGSTATSD_NON_LOCAL_TRAFFIC
      value: "true"
    - name: DD_ENABLE_PAYLOADS_EVENTS
      value: "true"
    - name: DD_ENABLE_PAYLOADS_SERIES
      value: "true"
    - name: DD_ENABLE_PAYLOADS_SERVICE_CHECKS
      value: "false"
    - name: DD_ENABLE_PAYLOADS_SKETCHES
      value: "false"
  logs:
    enabled: true
    containerCollectAll: true
    containerCollectUsingFiles: true
  apm:
    enabled: false
    portEnabled: false
    socketPath: /var/run/datadog/apm.socket
    hostSocketPath: /var/run/datadog/
  processAgent:
    enabled: false
    processCollection: false
    containerCollection: false
    processDiscovery: false
  orchestratorExplorer:
    enabled: false
    container_scrubbing:
      enabled: false
  systemProbe:
    enableTCPQueueLength: false
    enableOOMKill: true
    collectDNSStats: false
  podLabelsAsTags: 
    app: kube_app
  nodeLabelsAsTags:
    kubernetes.io/role: kube_role
  containerExcludeLogs: "name:k8s-sidecar name:proxy-agent name:agent name:coredns name:do-csi-plugin kube_namespace:kube-system"
  dogstatsd:
    port: 8125
    useSocketVolume: true
    socketPath: /var/run/datadog/dsd.socket
    hostSocketPath: /var/run/datadog/
    useHostPort: true
  confd:
    # https://github.com/DataDog/integrations-core/blob/master/mongo/datadog_checks/mongo/data/conf.yaml.example
    mongo.yaml: |-
      init_config: {}
      instances:
        - server: mongodb+srv://datadog:{{ .Values.MONGO_PASSWORD }}@{{ .Values.MONGO_HOST }}/admin
          dbnames:
            - admin
            - talk2robots
          collections:
            - talk2robots.users
          tls: true
          options:
            authSource: admin
            replicaSet: None
          additional_metrics:
            - metrics.commands
            - tcmalloc
            - top
            - collection
            - jumbo_chunks
clusterAgent:
  enabled: true
  replicas: 1
  # createPodDisruptionBudget: true