apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: radiant.space
  # Cert-Manager will put the resulting Secret in the same Kubernetes namespace as the Certificate.
  namespace: talk2robots
spec:
  # Secret name to create, where the private key and certificate should be stored.
  secretName: radiant.space
  # What Issuer to use for getting the certificate.
  issuerRef:
    name: letsencrypt-nginx-wcard
    kind: Issuer
    group: cert-manager.io
  # Common name to be used on the Certificate.
  commonName: "*.radiant.space"
  # List of DNS subjectAltNames to be set on the Certificate.
  dnsNames:
    - "radiant.space"
    - "*.radiant.space"