version: "3.7"

services:
  backend:
    image: talk2robots_backend:latest
    depends_on:
      - mongo
      - redis
    restart: always
    environment:
      REDIS_HOST: localhost
      REDIS_PASSWORD: ""
      BACKEND_BASE_URL: https://${CODESPACE_NAME}-80.${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN}
      BACKEND_LISTEN_ADDRESS: 0.0.0.0:8080
      BACKEND_LISTEN_URL: http://0.0.0.0:8080
      CLAUDE_API_KEY:
      OPENAI_API_KEY:
      GROK_API_KEY:
      FIREWORKS_API_KEY:
      STRIPE_TOKEN: setup-for-testing
      TELEGRAM_BOT_TOKEN:
      MONGO_DB_CONNECTION_STRING: mongodb://root:example@localhost:27017/?tls=false
      MONGO_DB_NAME: test
      SLACK_BOT_TOKEN: dev
      SLACK_SIGNING_SECRET: dev
      STRIPE_ENDPOINT_SECRET: dev
      STRIPE_ENDPOINT_SUFFIX: dev

      # setup to enable telegram system notifications
      TELEGRAM_SYSTEM_TOKEN: ""
      TELEGRAM_SYSTEM_TO: ""
    network_mode: "host"
    volumes:
      - ./data:/data

  nginx:
    image: nginx:1.19-alpine
    restart: always
    depends_on:
      - backend
    volumes:
      - ./infra/nginx-dev/nginx.conf:/etc/nginx/nginx.conf
    network_mode: "host"

  mongo:
    image: mongo:6.0.13
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    network_mode: "host"

  redis:
    image: redis:7.0.9-alpine
    restart: always
    environment:
      REDIS_PASSWORD: example
    network_mode: "host"
