name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ./backend/go.mod

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        run: make deps
        working-directory: ./backend

      - name: Build
        run: make build
        working-directory: ./backend

      - name: Format
        run: make fmt
        working-directory: ./backend

      - name: Vet
        run: make vet
        working-directory: ./backend

      - name: Lint
        run: make lint || true
        working-directory: ./backend

      - name: Test
        run: make test
        working-directory: ./backend
